### ISSUE TITLE
BigInt Layer

### ISSUE THREAD

**Issue by GQQQy** [cryptape/ckb-crypto#22]
代码实现(Botan项目提取)

**Comment by timfaner** [comment]
记得分配项目、标签、milestone。建议把issue分成更小的目标

**Comment by GQQQy** [comment]
全部提取.h头文件，进一步熟悉数据结构，阅读源码cpp文件熟悉接口。开始尝试运行大整数层的单个函数功能，为第二层做代码和理论准备

**Comment by GQQQy** [comment]
当全部提取之后发现，头文件和源文件的数量过于庞大，考虑是否按照botan项目的形式划分子路径。

**Comment by GQQQy** [comment]
> 
> 
> 当全部提取之后发现，头文件和源文件的数量过于庞大，考虑是否按照botan项目的形式划分子路径。

由此思考，在整个工程的角度来看，放在一级路径下十分不现实，文件数量过多不易于管理。

**Comment by GQQQy** [comment]
> 
> 
> 全部提取.h头文件，进一步熟悉数据结构，阅读源码cpp文件熟悉接口。开始尝试运行大整数层的单个函数功能，为第二层做代码和理论准备

提取.h文件的同时不应忽略其相应实现的.cpp文件，一般来说都会在同级目录下出现，注意不要忽略，往后回去再找的话十分麻烦。

**Comment by timfaner** [comment]
嗯嗯分一层肯定不行， 我已经在尝试分层级目录。目前主要问题是各个文件之间依赖关系有些复杂，和cmake结合有点困难，我正在尝试

**Comment by GQQQy** [comment]
> 
> 
> 嗯嗯分一层肯定不行， 我已经在尝试分层级目录。目前主要问题是各个文件之间依赖关系有些复杂，和cmake结合有点困难，我正在尝试

能否将上次编译好的整个工程push到git上，**包括CMake文件和configure.sh执行py脚本的命令，以及调用库的文件main.cpp代码**，这样我在编译调用库的时候也好有个基准，这些我在botan_based分支上并没有找到( ゜- ゜)つロ

**Comment by GQQQy** [comment]
成功生成botan下的elf文件，即可调用namespace botan，可以声明类BigInt，并且可以调用其类中的函数，接下来的工作就是掌握各种函数的使用方法

**Comment by timfaner** [comment]
差不多可以pull request来合并一次代码
