### ISSUE TITLE
目录结构更新

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#27]

**Comment by timfaner** [comment]
[参照](https://github.com/ttroy50/cmake-examples/)
分为两个CMake主项目，lib以及script 

### 目录结构
- lib
库文件相关 
- script
上链的代码相关

### lib内容
每层级为一个项目，每个项目下面对外api作为头文件

**Comment by timfaner** [comment]
测试怎么加？
看看用botan原生的还是用gtest？ 和clion怎么结合？
[clion guest教程](https://www.jetbrains.com/help/clion/creating-google-test-run-debug-configuration-for-test.html)

**Comment by GQQQy** [comment]
lib是否还要再分路径？同样的script是不是还要按照功能划分路径？

**Comment by timfaner** [comment]
直接在botan上改不太现实 项目过于庞大

**Comment by timfaner** [comment]
开发方案更改
