### ISSUE TITLE
botan在riscv下的测试

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#33]
选定一个函数测试其中能否生成正常运行的riscv目标。编译时候可以执行最小编译

**Comment by timfaner** [comment]
### ~~ckb-vm支持这些功能吗~~
- [ ] ~~posix1~~
- [ ] ~~posix_mlock~~
- [ ] dev_random~~
- [ ] proc_fs
- [ ] clock_gettime
- [ ] getauxval
- [ ] threads
- [ ] thread_local
- [ ] filesystem

~~这些模块在glibc中提供，ckb-vm支持glibc吗 ？~~

编译时候也会遇到 #13 的问题

都不支持

**Comment by timfaner** [comment]
botan 最小编译模块：base cpuid entropy rng utils 
最主要解决随机源 其次是cupid

**Comment by timfaner** [comment]
#36

**Comment by GQQQy** [comment]
最终编译出来的库，我们可以直接在C代码中调用，并且执行其中的某个函数吗？如果这样可以的话，一个rust脚本就可以执行全部的编译出来的密码库函数

**Comment by timfaner** [comment]
C的话需要暴露接口 C++可以
