### ISSUE TITLE
随机数生成器如何处理？

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#35]
大多说模块依赖随机数生成器，若系统没有熵源该如何处理？

**Comment by CipherWang** [comment]
为什么会需要这个模块，我猜是要做私钥生成和签名？但这两个工作都不应该在链上实现，都是在链外实现的，这样就可以依赖链外任何形式的熵源。

**Comment by timfaner** [comment]
这个是开发中遇到的一个研究点，开发中不是问题，之后开能据此展开研究。
