### ISSUE TITLE
Ed25519 签名算法在 GCC工具链下编译

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#39]
botan库中 Ed25519签名在gcc下实现

**Comment by timfaner** [comment]
https://github.com/hfzjcl/Documents/blob/master/About%2025519.md

**Comment by timfaner** [comment]
https://github.com/hfzjcl/Documents/blob/master/About%2025519.pdf

**Comment by GQQQy** [comment]
botan库遇到了玄学问题，完成时间要向后推迟两天

**Comment by timfaner** [comment]
这么问题嘞

**Comment by GaoGGGQY** [comment]
> botan库遇到了玄学问题，完成时间要向后推迟两天

finish

**Comment by GQQQy** [comment]
> botan库遇到了玄学问题，完成时间要向后推迟两天

finish in sig

**Comment by timfaner** [comment]
elf体积有多大？
