### ISSUE TITLE
BLS、原理调研

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#44]
### BLS原理调研
bls的原理
hash to curve
tate pairing 原理
等等

### 参考文献
short signatures from the weil pairing
等等

**Comment by timfaner** [comment]
### useful links
[pairing友好曲线](https://tools.ietf.org/id/draft-yonezawa-pairing-friendly-curves-02.html)
[bls12-381 参数](https://neuromancer.sk/std/bls/BLS12-381)

**Comment by Mz-Z** [comment]
https://github.com/ethereum/eth2.0-specs/blob/d07aa003076a772ec8f534b9175872ecf7ac514b/specs/phase0/beacon-chain.md#bls-signatures

**Comment by Mz-Z** [comment]
[eth2.0 bls](https://github.com/ethereum/eth2.0-specs/blob/d07aa003076a772ec8f534b9175872ecf7ac514b/specs/phase0/beacon-chain.md#bls-signatures)
[Hashing to Elliptic Curves](https://tools.ietf.org/id/draft-irtf-cfrg-hash-to-curve-06.html)
[draft-irtf-cfrg-bls-signature-02](https://tools.ietf.org/html/draft-irtf-cfrg-bls-signature-02)
[BLS12-381 For The Rest Of Us](https://hackmd.io/@benjaminion/bls12-381#Using-curve-BLS12-381)
