### ISSUE TITLE
PBC库调研

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#45]
### PBC库的使用
 能写一个简易版BLS签名
### PBC库涉及到的知识。
 与BLS相关的（曲线选择、各种限制等等）

### PBC库移植可能性  
  放在无os riscv环境下

-------
**DDL** : ``4-1 中午``

**Comment by DXPlus** [comment]
目前已大致理解BLS签名，包括签名和验证算法的原理，以及双线性映射；下一步进行PBC库的调研工作

**Comment by timfaner** [comment]
最好写一下看的产出、成果，不是进度汇报

**Comment by timfaner** [comment]
pbc库 type f 支持bn曲线，不支持bls曲线
