### ISSUE TITLE
Git pull request 以及issue测试

### ISSUE THREAD

**Issue by timfaner** [cryptape/ckb-crypto#7]

**Comment by Maellys** [comment]
关于issue、kanban、milestone的操作都不能在命令行完成吧？

**Comment by DXPlus** [comment]
how to send files to close issue by using command-line tools?

**Comment by timfaner** [comment]
请各位在这里尝试

> 关于issue、kanban、milestone的操作都不能在命令行完成吧？

不能 得在网页完成

**Comment by timfaner** [comment]
> how to send files to close issue by using command-line tools?

需要在网页完成
